version: ~> 1.0

env:
  global:
    - OFFICIAL_REPO="pcdshub/jet_tracking"
    # Doctr deploy key for pcdshub/jet_tracking
    - secure: "V2DzajEtsKUl0+J4pziJWuGPQ4q4kUdKs0V7xIdDxnzO6RmuI49tulurfr/HwMa1Euitiuc1SfIpA+rbaPs0xysbZWAG2mpqT7s/RvFZ/+/rTKp/4GZkH8hvS7/8INQTFImwpHUWiG1L+3sv9+3SM0h3CorvWsBnknIkllHu7Qh2dqfW0bK7bgSjn2wGkgoP53QF3BQne08U2n7mMkD0stibzZCODPwUMNNJYDSa/4yjyPO0DOEVFs7iox3ToZ352OFKHsMO+awcMCFN8gP/c7Al+xp4IBGLX0s4U0AQGru+JqKae3zwukq2pDyWWgieH5QpAfm/Ht7KKH4hnzGtj9AL81dC9RkXDLV3iSN0SNPrVlrjJNnQi9gTxsXHd2NwVF0kXgo+7oX/zoEpIn+Z6wfOfseO+KFFFYYz3ASKS1U8UZo5qyAcCFPHl0T0WEcYZVvfre1GQkpRRVnNvfJdEAN2rWMi+ovKcVnH8rhc4uPwxdR5vSAcI1xKJMS7OUI0edAm2LvIOh4+ri2et5WR4ulhpaVm5/iDBxqYaz/vGWy+vu+Q9UzrZuGP4igt+SqMMlXkrAaJhAURaKSnqOiVUZI4JCeQ+0f88N2SkupsYAjIc040tEKsBaLgjBL1BnouR1owGwBqv6yeMail8nW0HBRZMGyH/SI4ZvK/HCWBGMg="
    # enable the usage of versions menu which allow versioning of the docs
    # pages and not only the master branch
    - DOCTR_VERSIONS_MENU="1"
    # The name of the conda package
    - CONDA_PACKAGE="jet_tracking"
    # The folder containing the conda recipe (meta.yaml)
    - CONDA_RECIPE_FOLDER="conda-recipe"
    # Extra dependencies needed to run the test with Pip
    - PIP_EXTRAS="PyQt5"

import:
  # This import enables a set of standard python jobs including:
  # - Build
  #   - Anaconda Package Build
  # - Tests
  #   - Python Linter
  #   - Package Linter
  #   - Documentation
  #   - Python 3.6 - PIP based
  #   - Python 3.6, 3.7 & 3.8 - Conda base
  # - Deploy
  #   - Documentation using doctr
  #   - Conda Package - uploaded to pcds-dev and pcds-tag
  #   - PyPI
  - pcdshub/pcds-ci-helpers:travis/shared_configs/standard-python-conda-latest.yml
