api_msg:
  port: 5000

hutch: 'cxi'
experiment: 'cxix53419'
run: '1'
sim: false
ffb: true
evr_name: 'evr1'
event_code: 40 # x-ray on event code

det_map:
  name: 'DsdCsPad'
  shape:
#    - 1738
#    - 1742
    - 1942
    - 1940
  dtype: float32
  bins: 100

pv_map:
  1: 'CXI:JTRK:REQ:DIFF_INTENSITY'
  2: 'CXI:JTRK:REQ:I0'
  3: 'CXI:JTRK:REQ:RATIO'
  4: 'CXI:JTRK:REQ:DROPPED'
  #4: 'XCS:JTRK:REQ:JET_PEAK'
  #5: 'XCS:JTRK:REQ:JET_LOC'

ipm:
  #name: 'CXI-SB2-BMMON'
  #det: 'TotalIntensity'
  name: 'FEEGasDetEnergy'
  det: 'f_12_ENRC'

jet_cam:
  name: 'None'
  axis: 1

cal_params:
  azav_bins: 100
  events: 1000
  i0_bins: 30  # Number of bins for i0 hist cuts
  i0_reject: 0.1  # Percent below peak pin to make cut
  fit_points: 5  # Number of points at start and end of azav array to do line fit
  delta_bin: 3  # Number of azav bins around peak used for integration
