api_msg:
  port: 5000

hutch: 'mfx'
experiment: 'mfxx45919'
run: '1'
sim: false
ffb: true
event_code: 40 # x-ray on event code

det_map:
  name: 'epix10k2M'
  shape:
    - 1666
    - 1664
  dtype: float32
  bins: 100

pv_map:
  1: 'MFX:JTRK:REQ:DIFF_INTENSITY'
  2: 'MFX:JTRK:REQ:I0'
  3: 'MFX:JTRK:REQ:RATIO'
  4: 'MFX:JTRK:REQ:DROPPED'

ipm: 
  name: 'FEEGasDetEnergy'
  det: 'f_12_ENRC' 
#  name: 'MFX-DG2-BMMON'
#  det: 'TotalIntensity'
#  det: None

jet_cam:
  name: 'None'
  axis: 1

motor:
    name: 'MFX:PI1:MMS:01'

cal_params:
  azav_bins: 100
  events: 1000
  i0_bins: 30  # Number of bins for i0 hist cuts
  i0_reject: 0.1  # Percent below peak pin to make cut
  fit_points: 5  # Number of points at start and end of azav array to do line fit
  delta_bin: 7  # Number of azav bins around peak used for integration
